---
- name: Deploy Web Application with Redis Counter
  hosts: raspberry_pi    # This should match your host group in /etc/ansible/hosts
  become: true
  vars:
    app_dir: /opt/hello-counter
  
  tasks:
    # Create application directory
    - name: Ensure application directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
    
    # Copy application files
    - name: Copy application files
      synchronize:
        src: ./
        dest: "{{ app_dir }}/"
        rsync_opts:
          - "--exclude=.git"
      delegate_to: localhost
    
    # Deploy application
    - name: Deploy with docker-compose
      docker_compose:
        project_src: "{{ app_dir }}"
        state: present

