version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "80:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:

